language: objective-c
branches:
  only:
  - master
script:
  - travis_retry xcodebuild -workspace SilentRunnerDemoApp/SilentRunnerDemoApp.xcworkspace  -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' -scheme SilentRunnerDemoApp  clean build
osx_image: xcode8.2
