# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SilentRunnerDemoApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'SilentRunnerEngine'

  target 'SilentRunnerDemoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SilentRunnerDemoAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
